version: "3.9"
services:
  mailer:
    build:
      context: .
      dockerfile: Dockerfile.mailer
    container_name: mailer
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    external: true